sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
services: mongodb
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install "pymongo<3.3"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install "pillow<4.0"; fi
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=colony_print setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: cDtsbaWnscIdpYxA5lqLNm56XLW3Pxwdbekzvu6eg8v4QVk6xFhUekSssv58MBJtilMnnfjINNmJfNu/vpb5qaSEFsnIvP3T+rYhU6uMqXHgLdctCurxhbxAsq9R/WcOjgVfpIImAevIK0zSPN9w03H66APu934p1QyDtLXMSmI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
