dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.py2.txt
  - pip install -r extra.py2.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=colony_print setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: EZYbi6YXz8Y7huwOur/lrE9osNagWomr6ENvHhyzVeGjVzcGljuqS7jvSXwmPLu5Jt9v132XLjM2PCH8Hd9eyk3C2VDheEiAMeb2Q8MOMhGvbU/xdRIxQCp6VfPwRPhZD/txr0JaT0avgDaP0k47KVYY5IJfPCoDo7fpn21IGrU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
